### ISSUE TITLE
In case of multiple scans, it auto populates in serial?

### ISSUE THREAD

**Issue by 10xSebastian** [pape-io/barcode-scanner.js#11]
Asked by @smartmeter here: https://github.com/pape-io/barcode-scanner.js/issues/3#issuecomment-160251159

> On multiple scans, it auto populates in serial, one after another correct, like your test file included in the sample.

**Comment by 10xSebastian** [comment]
Yes, it populates in the same sequence the user scans things.

**Comment by smartmeter** [comment]
ok thanks
