### ISSUE TITLE
Where exactly the detection is happening in the library?

### ISSUE THREAD

**Issue by 10xSebastian** [pape-io/barcode-scanner.js#12]
Asked by @smartmeter here: https://github.com/pape-io/barcode-scanner.js/issues/3#issuecomment-160251159

> Can you please tell in the JS/coffee code file, how to look at where is the scanner detected, I want to see if the scanner has issues on wedging or the prefix, is there an option to turn on so we can see where it is. Also, can you tell me where this is happening, so I can debug please.

**Comment by 10xSebastian** [comment]
https://github.com/pape-io/barcode-scanner.js/blob/master/src/barcode-scanner.coffee#L46

**Comment by smartmeter** [comment]
ok thanks. Coffee is new to me :)   I wanted to write some funtions in coffee. You can close this thanks!  :100:
