### ISSUE TITLE
Which bar code technology do you recommend?

### ISSUE THREAD

**Issue by 10xSebastian** [pape-io/barcode-scanner.js#8]
Asked by @smartmeter here: https://github.com/pape-io/barcode-scanner.js/issues/3#issuecomment-160251159

> http://www.ciax.com/manuals/ref_app/values.htm , the first four seem to work for me, since they're ASCII mostly. Since, I am using my own numbering which one do you recommend for easy and quick test with this

**Comment by 10xSebastian** [comment]
I can recommend all the ASCI based technologies: Code 128, Code 39, Code 93

They are also more human friendly, as they are human readable

**Comment by smartmeter** [comment]
thanks I was thinking 128 or 39. Its not showing me the close button, if you want to close this its fine thanks again
